drone_landing_node:
  ros__parameters:
    x_pid:
      kp: 3.0
      ki: 0.0
      kd: 0.5
      dt: 0.1
      max: 2.0
      min: -2.0
    y_pid:
      kp: 3.0
      ki: 0.0
      kd: 0.5
      dt: 0.1
      max: 2.0
      min: -2.0
    z_pid:
      kp: 0.5
      ki: 0.0
      kd: 0.5
      dt: 0.1
      max: 0.6
      min: -0.6
    z_setpoint: 1.0