drone_landing_node:
  ros__parameters:
    x_pid:
      kp: 0.5
      ki: 0.0
      kd: 0.1
      dt: 0.1
      max: 1.0
      min: -1.0
    y_pid:
      kp: -0.5
      ki: 0.0
      kd: -0.1
      dt: 0.1
      max: 1.0
      min: -1.0
    z_pid:
      kp: 0.25
      ki: 0.0
      kd: 0.075
      dt: 0.1
      max: 0.5
      min: -0.5
    z_setpoint: 1.0